name: build

on:
  push:
    tags:
      - '*'
  workflow_dispatch: # This allows manual triggering

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Set Go import path
      run: go env -w GO111MODULE=on

    - name: Install dependencies
      run: go mod download    

    - name: Install protobuf
      run: sudo apt update && sudo apt install -y protobuf-compiler
    
    - name: Update front-end
      run: |
        make clean assets
        make mod-tidy

    - name: Build
      run: |
        make go-build
    
    - name: Package
      run: |
        make package

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Assets
      uses: dwenegar/upload-release-assets@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.create_release.outputs.id }}
        assets_path: .tarballs/
